################################################################################
#+
#  Module:	$KROOT/src/kss/nires/testall/data
#
#  Author:	JMader
#
#  Date:	2020-05-28
#
#  Description:	Makefile for $KROOT/src/kss/nires/testall/data
#
#  Revisions:
#-
################################################################################

# File to release
# (NOTE: Moving these to instrument dirs)
RELDAT = testall-nires.yaml

################################################################################
# KROOT boilerplate:
# Include general make rules, using default values for the key environment
# variables if they are not already set.

ifndef KROOT
        KROOT = /kroot
endif

ifndef RELNAM
        RELNAM = default
endif

ifndef RELDIR
        RELDIR = $(KROOT)/rel/$(RELNAM)
endif

include $(KROOT)/etc/config.mk
